def blue(text):
    return "\033[34m{}".format(text)
def yellow(text):
    return "\033[33m{}".format(text)
def green(text):
    return "\033[32m{}".format(text)
def white(text):
    return "\033[37m{}".format(text)
def purple(text):
    return "\033[35m{}".format(text)